/**
 * Food vs non-food (beverage/alcohol) classification of Toast menu groups.
 *
 * Replaces the flat `SalesEntry.foodSalesPct = 0.7` with a real split computed
 * from line items. We classify on READ (from the stored group name) rather than
 * baking a flag at sync time, so re-tuning this list re-classifies history.
 *
 * Seeded from Fergie's Café live menu (21 groups, probed 2026-06-27). Unknown
 * groups default to FOOD but are flagged `known:false` so they can be surfaced
 * for review instead of silently miscounted.
 */

// Explicit non-food groups (beverages, alcohol, retail). Lower-cased for match.
const NON_FOOD_GROUPS = new Set(
  [
    'Hot Drinks',
    'Juice',
    'Soda',
    'Non-Alc',
    'Cocktails',
    'Draught',
    'Wine',
    'Spirits',
    'Liqueur',
    'Beverage',
  ].map((s) => s.toLowerCase()),
)

// Explicit food groups (known, so not flagged for review).
const FOOD_GROUPS = new Set(
  [
    'Brunch',
    'Sides',
    'Sauces',
    'Kids',
    'Features',
    'Breakfast',
    'Snacks',
    'Lunch',
    'Dinner',
    'Weddings',
  ].map((s) => s.toLowerCase()),
)

// Keyword fallback for groups we haven't seen — catches obvious beverages.
const NON_FOOD_KEYWORDS = [
  'drink',
  'beverage',
  'soda',
  'juice',
  'coffee',
  'tea',
  'wine',
  'beer',
  'draught',
  'draft',
  'cocktail',
  'spirit',
  'liqueur',
  'liquor',
  'bar',
  'cider',
  'seltzer',
  'water',
]

// Groups to ignore entirely (Toast scaffolding, not real sales lines).
const IGNORE_KEYWORDS = ['toast tables', 'autogenerated', 'do not edit']

export interface GroupClass {
  isFood: boolean
  ignore: boolean
  /** false → unseen group classified by fallback; surface for admin review. */
  known: boolean
}

/** Classify a Toast menu-group name as food / non-food / ignore. */
export function classifyGroup(groupName: string | null | undefined): GroupClass {
  const g = (groupName ?? '').trim().toLowerCase()
  if (!g) return { isFood: true, ignore: false, known: false }
  if (IGNORE_KEYWORDS.some((k) => g.includes(k))) {
    return { isFood: false, ignore: true, known: true }
  }
  if (NON_FOOD_GROUPS.has(g)) return { isFood: false, ignore: false, known: true }
  if (FOOD_GROUPS.has(g)) return { isFood: true, ignore: false, known: true }
  if (NON_FOOD_KEYWORDS.some((k) => g.includes(k))) {
    return { isFood: false, ignore: false, known: false }
  }
  return { isFood: true, ignore: false, known: false }
}
